# Use root/example as user/password credentials
version: '3.1'

services:

  microblog:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: microblog:1.0-dev
    # restart: always
    # ports:
    #   - 5000:5000
    volumes:
      - .:/src
    environment:
      SECRET_KEY: 'you-will-never-guess'
      DB_HOST: db
      DB_ROOT_PASSWORD: root
      DB_NAME: microblog
      FLASK_ENV: development
      FLASK_DEBUG: 1
    networks:
      front:
      backend:

networks:

  front:
    external:
      name: front

  backend:
    external:
      name: backend

